-- Phase 1 P0-02: Force Row Level Security on All Tenant Tables
-- Converts RLS from ENABLE (opt-in) to FORCE on all 26 tenant-scoped tables.
-- This ensures that even when connecting as table owner (e.g. neondb_owner),
-- PostgreSQL RLS policies are strictly enforced and cannot be bypassed.

ALTER TABLE "amenities" FORCE ROW LEVEL SECURITY;
ALTER TABLE "amenity_slots" FORCE ROW LEVEL SECURITY;
ALTER TABLE "announcements" FORCE ROW LEVEL SECURITY;
ALTER TABLE "bills" FORCE ROW LEVEL SECURITY;
ALTER TABLE "bookings" FORCE ROW LEVEL SECURITY;
ALTER TABLE "buildings" FORCE ROW LEVEL SECURITY;
ALTER TABLE "daily_help" FORCE ROW LEVEL SECURITY;
ALTER TABLE "daily_help_attendance" FORCE ROW LEVEL SECURITY;
ALTER TABLE "daily_help_links" FORCE ROW LEVEL SECURITY;
ALTER TABLE "deliveries" FORCE ROW LEVEL SECURITY;
ALTER TABLE "emergency_alerts" FORCE ROW LEVEL SECURITY;
ALTER TABLE "events" FORCE ROW LEVEL SECURITY;
ALTER TABLE "floors" FORCE ROW LEVEL SECURITY;
ALTER TABLE "gates" FORCE ROW LEVEL SECURITY;
ALTER TABLE "helpdesk_tickets" FORCE ROW LEVEL SECURITY;
ALTER TABLE "notifications" FORCE ROW LEVEL SECURITY;
ALTER TABLE "parking_slots" FORCE ROW LEVEL SECURITY;
ALTER TABLE "payments" FORCE ROW LEVEL SECURITY;
ALTER TABLE "polls" FORCE ROW LEVEL SECURITY;
ALTER TABLE "unit_members" FORCE ROW LEVEL SECURITY;
ALTER TABLE "units" FORCE ROW LEVEL SECURITY;
ALTER TABLE "user_society_roles" FORCE ROW LEVEL SECURITY;
ALTER TABLE "vehicles" FORCE ROW LEVEL SECURITY;
ALTER TABLE "visitor_entries" FORCE ROW LEVEL SECURITY;
ALTER TABLE "visitor_invites" FORCE ROW LEVEL SECURITY;
ALTER TABLE "visitors" FORCE ROW LEVEL SECURITY;
